spring.application.name=chatbot-backend

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/chatbot_db
spring.datasource.username=root
spring.datasource.password=184932

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyBW2XrKgrGEo1R7SZuAjmnPCSKijPY5uA8
